apiVersion:       extensions/v1beta1
kind:             Deployment
metadata:
  name:           reshifter
spec:
  replicas:       1
  template:
    metadata:
      labels:
        app:      reshifter
    spec:
      containers:
      - name:     reshifter-app
        image:    quay.io/mhausenblas/reshifter:0.3.21
        ports:
        - containerPort: 8080
        env:
        - name:   ACCESS_KEY_ID
          value:  "Q3AM3UQ867SPQQA43P2F"
        - name:   SECRET_ACCESS_KEY
          value:  "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3T"
        - name: RS_ETCD_CLIENT_CERT
          value: "/tmp/etcd.client.cert"
        - name: RS_ETCD_CLIENT_KEY
          value: "/tmp/etcd.client.key"
        - name: RS_ETCD_CA_CERT
          value: "/tmp/etcd.ca.cert"
        volumeMounts:
         - name: ccert
           mountPath: "/tmp/etcd.client.cert"
         - name: ckey
           mountPath: "/tmp/etcd.client.key"
         - name: ca
           mountPath: "/tmp/etcd.ca.cert"
      volumes:
      - hostPath:
          path: /etc/pki/minion.crt
        name: ccert
      - hostPath:        
         path: /etc/pki/minion.key
        name: ckey
      - hostPath:
         path: /etc/pki/trust/anchors/SUSE_CaaSP_CA.crt
        name: ca
---
apiVersion:       v1
kind:             Service
metadata:
  name:           reshifter
spec:
  ports:
    - port:       8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
  selector:
    app:          reshifter
